export const runtimeCopy = {
  title: "Laisen Runtime",
  description: "Connect a wallet, deploy the protocol package, and release execution on Base Sepolia.",
  rails: {
    founder: "Founder",
    protocolPackage: "Package",
    control: "Authority",
    wallet: "Signer",
    deployment: "Protocol",
    summary: "Proof",
    activity: "Timeline",
    evidence: "Proof",
    calls: "Calls and tx",
  },
  center: {
    status: "Run",
    mission: "Mission",
    mode: "Mode",
    aiPlan: "AI plan",
    protocolPackage: "Protocol package",
    signal: "Signal",
    mandate: "Mandate",
    capabilities: "Function capability",
    execution: "Execution",
  },
  buttons: {
    openRuntime: "Open Runtime",
    connect: "Connect",
    disconnect: "Disconnect",
    switchNetwork: "Switch",
    deploy: "Deploy",
    deploying: "Deploying",
    launch: "Start Run",
    release: "Release to Base Sepolia",
    reject: "Reject",
    override: "Override",
    redirect: "Redirect",
    abort: "Abort",
    resume: "Resume AI",
    safeMode: "Use safe mode",
    reset: "Reset",
  },
  placeholder: {
    mission: "Describe the mission Laisen should run.",
  },
  modes: {
    live: "Standard",
    safe_mode: "Safe mode",
    hard_fail: "Failure test",
  },
} as const;
